# Generated by Django 5.1.1 on 2024-09-07 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couple_names', models.CharField(max_length=50, verbose_name='Nome do Casal')),
                ('wedding_datetime', models.DateTimeField(verbose_name='Data do Casamento')),
                ('ceremony_address', models.CharField(max_length=255, verbose_name='Endereço da Cerimônia')),
                ('reception_address', models.CharField(max_length=255, verbose_name='Endereço da Recepção')),
                ('ceremony_time', models.TimeField(verbose_name='Horário da Cerimônia')),
                ('reception_time', models.TimeField(verbose_name='Horário da Recepção')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='home/logo/', verbose_name='Logo')),
                ('primary_color', models.CharField(blank=True, max_length=7, null=True, verbose_name='Cor Primária')),
                ('secondary_color', models.CharField(blank=True, max_length=7, null=True, verbose_name='Cor Secundária')),
                ('terciary_color', models.CharField(blank=True, max_length=7, null=True, verbose_name='Cor Terciária')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('intro', 'Introdução'), ('text_1', 'Primeiro Texto'), ('text_2', 'Segundo Texto'), ('text_3', 'Terceiro Texto'), ('text_4', 'Quarto Texto'), ('text_5', 'Quinto Texto'), ('leave_a_message_text', 'Texto da Mensagem'), ('leave_a_message_text2', 'Texto 2 da Mensagem'), ('last_text', 'Último Texto'), ('footer', 'Rodapé'), ('about_us_text_1', 'Texto 1 Sobre Nós'), ('about_us_text_2', 'Texto 2 Sobre Nós'), ('about_us_text_3', 'Texto 3 Sobre Nós'), ('about_us_text_4', 'Texto 4 Sobre Nós'), ('gallery_text_1', 'Texto1 da Galeria'), ('gallery_text_2', 'Texto2 da Galeria')], max_length=50, verbose_name='Posição no Site')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtítulo')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Conteúdo')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('image', models.ImageField(upload_to='home/gallery/', verbose_name='Imagem')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('position', models.CharField(blank=True, choices=[('circles', 'Círculos'), ('gallery', 'Galeria')], max_length=10, null=True, verbose_name='Posição')),
                ('text_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='home.textcontent', verbose_name='Conteúdo de Texto')),
            ],
            options={
                'verbose_name': 'Galeria',
                'verbose_name_plural': 'Imagens',
            },
        ),
    ]
