# Generated by Django 5.1.1 on 2024-09-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('image', models.ImageField(upload_to='home/gifts/', verbose_name='Imagem')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço')),
            ],
            options={
                'verbose_name': 'Presente',
                'verbose_name_plural': 'Presentes',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('will_go', models.BooleanField(blank=True, null=True, verbose_name='Confirmado')),
                ('self_created', models.BooleanField(default=False, verbose_name='Criado pelo Usuário')),
            ],
            options={
                'verbose_name': 'Convidado',
                'verbose_name_plural': 'Convidados',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
            },
        ),
        migrations.AddField(
            model_name='settings',
            name='account_holder',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Titular da Conta'),
        ),
        migrations.AddField(
            model_name='settings',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do Banco'),
        ),
        migrations.AddField(
            model_name='settings',
            name='pix_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave PIX'),
        ),
        migrations.AddField(
            model_name='settings',
            name='pix_type',
            field=models.CharField(blank=True, choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ'), ('E-mail', 'E-mail'), ('Telefone', 'Telefone')], max_length=50, null=True, verbose_name='Tipo de Chave PIX'),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='position',
            field=models.CharField(choices=[('intro', 'Introdução'), ('text_1', 'Primeiro Texto'), ('text_2', 'Segundo Texto'), ('text_3', 'Terceiro Texto'), ('text_4', 'Quarto Texto'), ('text_5', 'Quinto Texto'), ('leave_a_message_text', 'Texto da Mensagem'), ('leave_a_message_text2', 'Texto 2 da Mensagem'), ('last_text', 'Último Texto'), ('about_us_text_1', 'Texto 1 Sobre Nós'), ('about_us_text_2', 'Texto 2 Sobre Nós'), ('about_us_text_3', 'Texto 3 Sobre Nós'), ('about_us_text_4', 'Texto 4 Sobre Nós'), ('about_us_text_5', 'Texto 5 Sobre Nós'), ('gallery_text_1', 'Texto1 da Galeria'), ('gallery_text_2', 'Texto2 da Galeria')], max_length=50, verbose_name='Posição no Site'),
        ),
    ]
