# Generated by Django 5.1.1 on 2024-09-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_gift_guest_message_settings_account_holder_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textcontent',
            options={'verbose_name': 'Conteúdo de Texto', 'verbose_name_plural': 'Conteúdos de Texto'},
        ),
        migrations.AddField(
            model_name='settings',
            name='site_url',
            field=models.URLField(default='', verbose_name='URL do Site'),
            preserve_default=False,
        ),
    ]
