# Generated by Django 5.1.1 on 2024-09-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_textcontent_options_settings_site_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='site_description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Site'),
        ),
        migrations.AddField(
            model_name='settings',
            name='site_image',
            field=models.ImageField(blank=True, null=True, upload_to='home/site_image/', verbose_name='Imagem do Site'),
        ),
    ]
