# Generated by Django 5.1.1 on 2024-09-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_settings_site_description_settings_site_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='song',
            field=models.FileField(blank=True, null=True, upload_to='home/song/', verbose_name='Música'),
        ),
    ]
