# Generated by Django 5.1.1 on 2024-09-09 22:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_settings_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='song',
            field=models.FileField(blank=True, null=True, upload_to='home/song/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg'])], verbose_name='Música'),
        ),
    ]
