# Generated by Django 5.1.1 on 2024-09-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_settings_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='BridalShowerGiftSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('link', models.URLField(verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Sugestão de Presente do Chá de Panela',
                'verbose_name_plural': 'Sugestões de Presentes do Chá de Panela',
            },
        ),
        migrations.AddField(
            model_name='settings',
            name='hide_bridal_shower_gift',
            field=models.BooleanField(default=False, verbose_name='Esconder Presentes do Chá de Panelas'),
        ),
        migrations.AddField(
            model_name='settings',
            name='hide_gallery',
            field=models.BooleanField(default=False, verbose_name='Esconder Galeria'),
        ),
        migrations.AddField(
            model_name='settings',
            name='hide_gifts',
            field=models.BooleanField(default=False, verbose_name='Esconder Presentes'),
        ),
        migrations.AddField(
            model_name='settings',
            name='hide_info',
            field=models.BooleanField(default=False, verbose_name='Esconder Informações'),
        ),
        migrations.AddField(
            model_name='settings',
            name='hide_rsvp',
            field=models.BooleanField(default=False, verbose_name='Esconder RSVP'),
        ),
        migrations.CreateModel(
            name='BridalShowerGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('image', models.ImageField(upload_to='home/bridal_shower_gifts/', verbose_name='Imagem')),
                ('category', models.CharField(choices=[('cozinha', 'Cozinha'), ('cama_mesa_banho', 'Cama, Mesa e Banho'), ('decoracao', 'Decoração'), ('eletrodomesticos', 'Eletrodomésticos'), ('outros', 'Outros')], max_length=50, verbose_name='Categoria')),
                ('guest_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do Convidado')),
                ('guest_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do Convidado')),
                ('guest_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do Convidado')),
                ('suggestions', models.ManyToManyField(blank=True, to='home.bridalshowergiftsuggestion', verbose_name='Sugestões de Presente')),
            ],
            options={
                'verbose_name': 'Presente do Chá de Panela',
                'verbose_name_plural': 'Presentes do Chá de Panela',
            },
        ),
    ]
