# Generated by Django 5.1.1 on 2024-09-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_bridalshowergiftsuggestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='bridal_shower_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço do Chá de Panela'),
        ),
        migrations.AddField(
            model_name='settings',
            name='bridal_shower_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Chá de Panela'),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='position',
            field=models.CharField(choices=[('intro', 'Introdução'), ('text_1', 'Primeiro Texto'), ('text_2', 'Segundo Texto'), ('text_3', 'Terceiro Texto'), ('text_4', 'Quarto Texto'), ('text_5', 'Quinto Texto'), ('leave_a_message_text', 'Texto da Mensagem'), ('leave_a_message_text2', 'Texto 2 da Mensagem'), ('last_text', 'Último Texto'), ('about_us_text_1', 'Texto 1 Sobre Nós'), ('about_us_text_2', 'Texto 2 Sobre Nós'), ('about_us_text_3', 'Texto 3 Sobre Nós'), ('about_us_text_4', 'Texto 4 Sobre Nós'), ('about_us_text_5', 'Texto 5 Sobre Nós'), ('gallery_text_1', 'Texto1 da Galeria'), ('gallery_text_2', 'Texto2 da Galeria'), ('bridal_shower_text', 'Texto do Chá de Panela')], max_length=50, verbose_name='Posição no Site'),
        ),
    ]
