# Generated by Django 5.1.1 on 2024-09-17 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_bridalshowergift_suggestions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BridalShowerGiftColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=7, verbose_name='Cor')),
            ],
            options={
                'verbose_name': 'Cor do Presente do Chá de Panela',
                'verbose_name_plural': 'Cores do Presente do Chá de Panela',
            },
        ),
        migrations.RemoveField(
            model_name='bridalshowergift',
            name='guest_email',
        ),
        migrations.RemoveField(
            model_name='bridalshowergift',
            name='guest_name',
        ),
        migrations.RemoveField(
            model_name='bridalshowergift',
            name='guest_phone',
        ),
        migrations.AddField(
            model_name='bridalshowergift',
            name='colors',
            field=models.ManyToManyField(related_name='gifts_colors', to='home.bridalshowergiftcolor', verbose_name='Cores'),
        ),
        migrations.CreateModel(
            name='BridalShowerGiftQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor')),
                ('guest_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do Convidado')),
                ('guest_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do Convidado')),
                ('guest_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do Convidado')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='home.bridalshowergift')),
            ],
            options={
                'verbose_name': 'Cota do Presente do Chá de Panela',
                'verbose_name_plural': 'Cotas do Presente do Chá de Panela',
            },
        ),
    ]
