# Generated by Django 5.1.1 on 2024-09-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_bridalshowergiftcolor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bridalshowergiftcolor',
            options={'verbose_name': 'Cor do Presente do CdP', 'verbose_name_plural': 'Cores do Presente do CdP'},
        ),
        migrations.AlterModelOptions(
            name='bridalshowergiftquota',
            options={'verbose_name': 'Cota do Presente do CdP', 'verbose_name_plural': 'Cotas do Presente do CdP'},
        ),
        migrations.AlterModelOptions(
            name='bridalshowergiftsuggestion',
            options={'verbose_name': 'Sugestão de Chá de Panela', 'verbose_name_plural': 'Sugestões de Chá de Panela'},
        ),
        migrations.AddField(
            model_name='bridalshowergiftcolor',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
