# Generated by Django 5.1.1 on 2024-09-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_bridalshowergiftcolor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridalshowergift',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do Convidado'),
        ),
        migrations.AddField(
            model_name='bridalshowergift',
            name='guest_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do Convidado'),
        ),
        migrations.AddField(
            model_name='bridalshowergift',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do Convidado'),
        ),
        migrations.DeleteModel(
            name='BridalShowerGiftQuota',
        ),
    ]
