# Generated by Django 5.1.1 on 2024-09-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_bridalshowergift_guest_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bridalshowergift',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Presente do Chá de Panela', 'verbose_name_plural': 'Presentes do Chá de Panela'},
        ),
        migrations.AlterField(
            model_name='bridalshowergift',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='gifts_colors', to='home.bridalshowergiftcolor', verbose_name='Cores'),
        ),
    ]
