# Generated by Django 5.1.1 on 2024-09-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_bridalshowergift_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='hide',
            field=models.BooleanField(default=False, verbose_name='Esconder'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='hide_title',
            field=models.BooleanField(default=False, verbose_name='Esconder Título'),
        ),
    ]
