# Generated by Django 5.1.1 on 2024-10-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_bridalshowergift_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridalshowergift',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='bridalshowergift',
            name='way_to_gift',
            field=models.CharField(blank=True, choices=[('take', 'Levar no dia'), ('send', 'Enviar pela internet'), ('money', 'Dar o dinheiro')], max_length=50, null=True, verbose_name='Forma de Presentear'),
        ),
    ]
