# Generated by Django 5.2.8 on 2025-11-30 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('home', '0016_bridalshowergift_price_bridalshowergift_way_to_gift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gift',
            options={'ordering': ['-price'], 'verbose_name': 'Presente', 'verbose_name_plural': 'Presentes'},
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='position',
            field=models.CharField(choices=[('intro', 'Introdução'), ('text_1', 'Primeiro Texto'), ('text_2', 'Segundo Texto'), ('text_3', 'Terceiro Texto'), ('text_4', 'Quarto Texto'), ('text_5', 'Quinto Texto'), ('leave_a_message_text', 'Texto da Mensagem'), ('leave_a_message_text2', 'Texto 2 da Mensagem'), ('last_text', 'Último Texto'), ('about_us_text_1', 'Texto 1 Sobre Nós'), ('about_us_text_2', 'Texto 2 Sobre Nós'), ('about_us_text_3', 'Texto 3 Sobre Nós'), ('about_us_text_4', 'Texto 4 Sobre Nós'), ('about_us_text_5', 'Texto 5 Sobre Nós'), ('gallery_text_1', 'Texto1 da Galeria'), ('gallery_text_2', 'Texto2 da Galeria'), ('gift_list_text', 'Texto da Lista de Presentes'), ('bridal_shower_text', 'Texto do Chá de Panela')], max_length=50, verbose_name='Posição no Site'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('payment_id', models.CharField(max_length=100, unique=True, verbose_name='ID do Pagamento')),
                ('payment_status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('in_process', 'Em Processamento'), ('rejected', 'Rejeitado'), ('cancelled', 'Cancelado')], max_length=50, verbose_name='Status do Pagamento')),
                ('payer_name', models.CharField(max_length=100, verbose_name='Nome do Pagador')),
                ('payer_email', models.EmailField(max_length=254, verbose_name='Email do Pagador')),
                ('payer_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do Pagador')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Pago')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Método de Pagamento')),
                ('installments', models.IntegerField(default=1, verbose_name='Parcelas')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
